[apic]
url = "sandboxapicdc.cisco.com"
username = "admin"
password = "ciscopsdt"

[data]
src = ".data"

[fabricNodes]
src = "fabric_membership.csv"

[[tenants]]
name = "ABC-DC5"
description = "DC5 in Liverpool"

[[tenants]]
name = "MGMT"
description = "Management Tenant"
