
[apic]
  password = "ciscopsdt"
  url = "sandboxapicdc.cisco.com"
  username = "admin"

[[nodes]]
  id = 901
  name = "spine-901"
  pod = 1
  role = "spine"
  serial = "ABC2002W1XF"

[[nodes]]
  id = 902
  name = "spine-902"
  pod = 1
  role = "spine"
  serial = "ABC2002W1WJ"

[[nodes]]
  id = 111
  name = "leaf-111"
  pod = 1
  role = "leaf"
  serial = "ABC1952T9YC"

[[nodes]]
  id = 112
  name = "leaf-112"
  pod = 1
  role = "leaf"
  serial = "ABC1952T92U"

[[nodes]]
  id = 113
  name = "leaf-113"
  pod = 1
  role = "leaf"
  serial = "ABC1952T93M"

[[nodes]]
  id = 114
  name = "leaf-114"
  pod = 1
  role = "leaf"
  serial = "ABC1950T9JZ"

[[nodes]]
  id = 115
  name = "leaf-115"
  pod = 1
  role = "leaf"
  serial = "ABC1952R531"

[[sites]]
  description = "Liverpool HQ"
  name = "liverpool"

  [[sites.buildings]]
    description = "John Moores Main Building"
    name = "john-moores"

    [[sites.buildings.floors]]
      description = "First Floor"
      name = "floor-01"

    [[sites.buildings.floors]]
      description = "Second Floor"
      name = "floor-02"

      [[sites.buildings.floors.rooms]]
        description = "Main Server Room"
        name = "room-01"

        [[sites.buildings.floors.rooms.rows]]
          description = "Main Row"
          name = "row-01"

          [[sites.buildings.floors.rooms.rows.racks]]
            description = "Main Rack"
            name = "rack-01"
